export enum ROLE {
  LEADER = "LEADER",
  VICE_LEADER = "VICE_LEADER",
  MEMBER = "MEMBER",
  HOST = "HOST"
}

export enum WEEK_DAY {
  MONDAY = "MONDAY",
  TUESDAY = "TUESDAY",
  WEDNESDAY = "WEDNESDAY",
  THURSDAY = "THURSDAY",
  FRIDAY = "FRIDAY",
  SATURDAY = "SATURDAY",
  SUNDAY = "SUNDAY"
}